FORMAT: 1A
HOST: http://dp2.iamallama.com/api

# DP2

API reference for mobile apps. Uses JWT authentication.

## Auth [/login]

### Login [GET]

Log a registered client giving email and password. On success, return a valid token


+ Request (application/json)

        {
            "email": "kbrekke@yahoo.com",
            "password": "secret"
        }


+ Response 200 (application/json)

        {
            "token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOjEsImlzcyI6Imh0dHA6Ly9kcDIuYXBwL2FwaS9sb2dpbiIsImlhdCI6MTUwOTM3ODI4NywiZXhwIjoxNTA5MzgxODg3LCJuYmYiOjE1MDkzNzgyODcsImp0aSI6ImVvZ2Z3dFVvZUpBZDBNT3kifQ.teKhDkjS2B_zQa80WcnD94AXHKwLQQWGU3ReVpwQcVU"
        }
        
+ Response 401 (application/json)

        {
            "error": "invalid_credentials"
        }

## Token [/refreshToken]

### Refresh [POST]

As tokens may expire, you can refresh it.

+ Request (application/json)
    
    + Headers
        
            Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOjEsImlzcyI6Imh0dHA6Ly9kcDIuYXBwL2FwaS9sb2dpbiIsImlhdCI6MTUwOTM3ODI4NywiZXhwIjoxNTA5MzgxODg3LCJuYmYiOjE1MDkzNzgyODcsImp0aSI6ImVvZ2Z3dFVvZUpBZDBNT3kifQ.teKhDkjS2B_zQa80WcnD94AXHKwLQQWGU3ReVpwQcVU


+ Response 200 (application/json)

    + Headers
        
            Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOjEsImlzcyI6Imh0dHA6Ly9kcDIuYXBwL2FwaS9yZWZyZXNoVG9rZW4iLCJpYXQiOjE1MDkzNzgyODcsImV4cCI6MTUwOTM4MjU0NSwibmJmIjoxNTA5Mzc4OTQ1LCJqdGkiOiJ1aVF5TWdnZW42Rzc4dnpRIn0.k5ve1OxPRc_4yi7IfDRa3iCutf69lC7B2epRKRVrSQ0